_target_: agent.td3.TD3Agent
nstep: ${buffer.nstep}
hidden_dim: [512, 512]
target_update_interval: 2
lr_actor: 3.0e-4
lr_critic: 3.0e-4
gamma: 0.99
tau: 0.005
policy_update_interval: 2
policy_noise: 0.1
noise_clip: 0.3
eps_schedule: linear(1, 0.05, 1000, 100000)